src/Entity/Sale.php
<?php

namespace App\Entity;

use App\Repository\SaleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SaleRepository::class)
 * @UniqueEntity(
 *     fields={"refId"},
 *     message="Cet identifiant est unique"
 * )
 * @ORM\HasLifecycleCallbacks()
 */
class Sale
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=SimCard::class)
     * @Assert\Valid()
     * @Assert\NotBlank(message="Veuillez sélectionner un numéro valid")
     */
    private $msisdn;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $amount = 0;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $dComm = 0;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $posComm = 0;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $transactionAt;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class)
     */
    private $type;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     * @Assert\Regex(
     *     pattern="^[0-9]+$",
     *     htmlPattern="^[0-9]+$",
     *     message="Le numéro doit être composé de chiffre uniquement"
     * )
     */
    private $refId;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $dCommCalc;

    /**
     * @ORM\Column(type="float")
     */
    private $posCommCalc;



    /**
     * @param $amount
     * @return float
     */
    private function getAGNTCommission($amount)
    {
        $commission = 0 ;
        if($amount >= 500 and $amount<=5000){
            $commission = 45;
        }elseif($amount > 5000 and $amount <= 15000){
            $commission = 200;
        }elseif($amount > 15000 and $amount <= 20000){
            $commission = 200 ;
        }elseif($amount > 20000 and $amount <= 50000){
            $commission = 400 ;
        }elseif($amount > 50000 and $amount <= 100000){
            $commission = 900 ;
        }elseif($amount > 100000 and $amount <= 200000){
            $commission = 1500 ;
        }elseif($amount > 200000 and $amount <= 300000){
            $commission = 2200 ;
        }elseif($amount > 300000 and $amount <= 500000){
            $commission = 2475 ;
        }elseif($amount > 500000 and $amount <= 850000){
            $commission = 2585 ;
        }elseif($amount > 850000 and $amount <= 1000000){
            $commission = 2695 ;
        }elseif($amount > 1000000 and $amount <= 1500000){
            $commission = 3190 ;
        }elseif($amount > 1500000 and $amount <= 2000000){
            $commission = 4785 ;
        }
        return $commission;
    }

    /**
     * @param $amount
     * @return float
     */
    private function getCSINCommission($amount)
    {
        $commission = 0 ;
        if($amount >=500 and $amount<=5000){
            $commission = 25;
        }elseif($amount > 5000 and $amount <= 15000){
            $commission = 75;
        }elseif($amount > 15000 and $amount <= 20000){
            $commission = 150 ;
        }elseif($amount > 20000 and $amount <= 50000){
            $commission = 150 ;
        }elseif($amount > 50000 and $amount <= 100000){
            $commission = 300 ;
        }elseif($amount > 100000 and $amount <= 200000){
            $commission = 400 ;
        }elseif($amount > 200000 and $amount <= 300000){
            $commission = 400 ;
        }elseif($amount > 300000 and $amount <= 500000){
            $commission = 470 ;
        }elseif($amount > 500000 and $amount <= 850000){
            $commission = 500 ;
        }elseif($amount > 850000 and $amount <= 1000000){
            $commission = 750 ;
        }elseif($amount > 1000000 and $amount <= 1500000){
            $commission = 1000 ;
        }/*elseif($amount > 1500000 and $amount <= 2000000){
            $commission = 4785 ;
        }*/

        return $commission;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initialized()
    {
        $this->updateAt = new \DateTime();
        if($this->getSimProfile()=='AGNT'){
            $this->dCommCalc = $this->calcCommission() ;
            $this->posCommCalc = 0;
        }elseif ($this->getSimProfile()=='DISTRO'){
            $this->dCommCalc = $this->calcCommission() * (20/100);
            $this->posCommCalc = $this->calcCommission() * (80/100);
        }else{
            $this->dCommCalc = 0;
            $this->posCommCalc = 0;
        }

    }

    public function getMsisdn(): ?SimCard
    {
        return $this->msisdn;
    }

    public function setMsisdn(?SimCard $msisdn): self
    {
        $this->msisdn = $msisdn;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(?float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDComm(): ?float
    {
        return $this->dComm;
    }

    public function setDealerCommission(?float $dComm): self
    {
        $this->dComm = $dComm;

        return $this;
    }

    public function getPosComm(): ?float
    {
        return $this->posComm;
    }

    public function setPosComm(?float $posComm): self
    {
        $this->posComm = $posComm;

        return $this;
    }

    public function getTransactionAt(): ?\DateTimeInterface
    {
        return $this->transactionAt;
    }

    public function setTransactionAt(?\DateTimeInterface $transactionAt): self
    {
        $this->transactionAt = $transactionAt;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRefId(): ?string
    {
        return $this->refId;
    }

    public function setRefId(?string $refId): self
    {
        $this->refId = $refId;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(?\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function calcCommission()
    {
        $withdrawal = ['AGNT', 'AWITH', 'WITH', 'APPAGNT'];
        $type = $this->getType()->getTitle();
        if(in_array($type,$withdrawal)){
            $commission = $this->getAGNTCommission($this->getAmount());
        }elseif ($type ='CSIN'){
            $commission = $this->getCSINCommission($this->getAmount());
        }
        return $commission;
    }

    public function getSimProfile()
    {
        if($this->getMsisdn()){
            return $this->getMsisdn()->getProfile()->getTitle();
        }else{
            return null;
        }

    }

    public function getDCommCalc(): ?float
    {
        return $this->dCommCalc;
    }

    public function setDCommCalc(?float $dCommCalc): self
    {
        $this->dCommCalc = $dCommCalc;

        return $this;
    }

    public function getPosCommCalc(): ?float
    {
        return $this->posCommCalc;
    }

    public function setPosCommCalc(float $posCommCalc): self
    {
        $this->posCommCalc = $posCommCalc;

        return $this;
    }



}

src/Entity/Trader.php
<?php

namespace App\Entity;

use App\Repository\TraderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TraderRepository::class)
 * @Vich\Uploadable()
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"fullName"},
 *     message="Cet nom est déjà en registrer",
 *     )
 */
class Trader
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=SimCard::class, inversedBy="trader", cascade={"persist", "remove"})
     * @Assert\Valid()
     * @Assert\NotBlank(message="Veuillez choisir un numéro valide")
     */
    private $msisdn;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Veuillez saisir un nom valide")
     */
    private $fullName;

    /**
     * @Assert\File(
     *     maxSize="1024k",
     *     maxSizeMessage="Le fichier ne doit pas excéder 1024Ko"
     * )
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="pictureName")
     * @var File|null
     */
    private $pictureFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pictureName;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isTrader;

    /**
     * @ORM\ManyToOne(targetEntity=Region::class, inversedBy="traders")
     * @Assert\Valid()
     */
    private $region;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isActive = true;



    /**
     * @ORM\OneToMany(targetEntity=Control::class, mappedBy="trader", cascade={"persist"})
     */
    private $controls;

    public function __construct()
    {
        $this->controls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     *
     */
    public function initialized()
    {
        $this->updateAt = new \DateTime();
    }

    public function getMsisdn(): ?SimCard
    {
        return $this->msisdn;
    }

    public function setMsisdn(?SimCard $msisdn): self
    {
        $this->msisdn = $msisdn;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getPictureName(): ?string
    {
        return $this->pictureName;
    }

    public function setPictureName(?string $pictureName): self
    {
        $this->pictureName = $pictureName;

        return $this;
    }

    /**
     * @param File|UploadedFile|null $pictureFile
     * @throws \Exception
     */
    public function setPictureFile(?File  $pictureFile = null): void
    {
        $this->pictureFile = $pictureFile;
        if (null !== $pictureFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updateAt = new \DateTimeImmutable();
        }

    }

    public function getPictureFile(): ?File
    {
        return $this->pictureFile;
    }


    public function getIsTrader(): ?bool
    {
        return $this->isTrader;
    }

    public function setIsTrader(?bool $isTrader): self
    {
        $this->isTrader = $isTrader;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(?\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(?bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }


    /**
     * @return Collection|Control[]
     */
    public function getControls(): Collection
    {
        return $this->controls;
    }

    public function addControl(Control $control): self
    {
        if (!$this->controls->contains($control)) {
            $this->controls[] = $control;
            $control->setTrader($this);
        }

        return $this;
    }

    public function removeControl(Control $control): self
    {
        if ($this->controls->contains($control)) {
            $this->controls->removeElement($control);
            // set the owning side to null (unless already changed)
            if ($control->getTrader() === $this) {
                $control->setTrader(null);
            }
        }

        return $this;
    }

    public function getName()
    {
        return $this->getMsisdn()->getName();
    }
}

src/Controller/SaleController.php
<?php

namespace App\Controller;

use App\Entity\Sale;
use App\Form\SaleType;
use App\Repository\SaleRepository;
use App\Service\PointofsaleStat;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SaleController extends AbstractController
{
    private $manager;
    private $repository;

    public function __construct(EntityManagerInterface $manager, SaleRepository $repository)
    {
        $this->manager = $manager;
        $this->repository = $repository;
    }

    /**
     * @Route("/sales", name="sale")
     * @return Response
     * @IsGranted("ROLE_ADMIN")
     */
    public function index():Response
    {
        $sales = $this->repository->findSaleByMonth();

        $columnHeaders = $this->repository->findDistinctMonth();
        return $this->render('sale/index.html.twig', [
            'sales' => $sales,
            'columnHeaders' => $columnHeaders
        ]);
    }

    private function crossTab($date, $sales)
    {
        $saleTab = [];
        foreach ($date as $d){
            $saleTab[] = $d;
        }
        return $saleTab;
    }
    /**
     * @param Request $request
     * @return Response
     * @Route("/sales/add", name="sale_add")
     * @IsGranted("ROLE_ADMIN")
     */
    public function create(Request $request):Response
    {

        $sale = new Sale();
        $form = $this->createForm(SaleType::class, $sale);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $this->manager->persist($sale);
            $this->manager->flush();
            $this->addFlash('success', "La transaction <strong>{$sale->getRefId()}</strong> a bien été ajouter");
            return $this->redirectToRoute('sale');
        }
        return $this->render('sale/create.html.twig', [
            'form' => $form->createView(),
        ]);

    }

    /**
     * @param Request $request
     * @param Sale $sale
     * @return Response
     * @Route("/sales/{id}/edit", name="sale_edit")
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function edit(Request $request, Sale $sale):Response
    {

        $form = $this->createForm(SaleType::class, $sale);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $this->manager->persist($sale);
            $this->manager->flush();
            $this->addFlash('success', "La transaction <strong>{$sale->getRefId()}</strong> a bien été modifier");
            return $this->redirectToRoute('sale');
        }
        return $this->render('sale/create.html.twig', [
            'form' => $form->createView(),
            'sale' => $sale,
        ]);
    }

    /**
     * @param Sale $sale
     * @return Response
     * @Route("/sales/{id}/delete}", name="sale_delete")
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function delete(Sale $sale):Response
    {
        $this->addFlash('success', "La transaction <strong>{$sale->getRefId()}</strong> a bien été supprimer");
        $this->manager->remove($sale);
        $this->manager->flush();
        return  $this->redirectToRoute('sale');
    }




    /**
     * @param PointofsaleStat $pointofsaleStat
     * @param $date
     * @return Response
     * @Route("/admin/sales/{date}", name="sale_illegal")
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function showIllegal(PointofsaleStat $pointofsaleStat, $date):Response
    {
        $sales = $pointofsaleStat->getIllegalSale($date);
        return $this->render('sale/illegalSale.html.twig', [
            'sales' => $sales,
        ]);
    }


    /**
     * @param Sale $sale
     * @return Response
     * @Route("/admin/sales/{id}", name="sale_show")
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function show(Sale $sale):Response
    {

        return $this->render('sale/show.html.twig', [
            'sale' => $sale,
        ]);
    }
}

templates/sale/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-lg-6">
        <fieldset class="form-group">
            <legend><span>Identification</span></legend>
            {{ form_row(form.refId) }}
            {{ form_row(form.msisdn) }}
            <div class="row">
                <div class="col-sm-6">{{ form_row(form.transactionAt) }}</div>
                <div class="col-sm-6">{{ form_row(form.type) }}</div>
            </div>


        </fieldset>
    </div>
    <div class="col-lg-6">
        <fieldset class="form-group">
            <legend><span>Commission</span></legend>
            {{ form_row(form.amount) }}
            {{ form_row(form.dComm) }}
            {{ form_row(form.posComm) }}
        </fieldset>
    </div>
</div>


<div class="form-buttons-w text-right compact">
    <button class="btn btn-primary" type="submit"> Valider</button>
</div>
{{ form_end(form) }}

templates/sale/create.html.twig
{% extends 'base.html.twig' %}
{% block title %}Transaction{% endblock %}
{% block body %}
    <div class="content-box">
        <div class="row">
            <div class="col-sm-12">
                <div class="element-wrapper">
                    <div class="element-box">
                        <h5 class="form-header">
                            {% if sale is defined %}
                                Modification de la transaction : <strong>{{ sale.refId }}</strong>
                            {% else %}
                                Enregistrement d'une nouvel transaction.
                            {% endif %}
                        </h5>
                        {{ include('sale/_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/sale/illegalSale.html.twig
{% extends 'base.html.twig' %}
{% block title %}

{% endblock %}
{% block body %}
    <div class="content-box">
        <div class="row">
            <div class="col-sm-12">
                <div class="element-wrapper">
                    <h6 class="element-header">
                        Tableau des transactions illégales
                    </h6>
                </div>
            </div>
        </div>
        <div class="element-box">
            <div class="table-responsive">
                <table id="dataTable1" width="100%" class="table table-striped table-lightfont">
                    <thead>
                    <tr>
                        <th></th>
                        <th>id</th>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Nom Point</th>
                        <th>Profil</th>
                        <th>Montant</th>
                        <th>Commission Dealer</th>
                        <th>Commission Dealer Calculer</th>
                        <th>Commission PDV</th>
                        <th>Commission PDV calculer</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if sales  %}
                        {% for sale in sales %}
                            <tr>
                                <td class="text-center">{{ loop.index0+1 }}</td>
                                <th>{{ sale.id  }}</th>
                                <th>{{ sale.transactionAt | date("F jS \\a\\t g:ia") }}</th>
                                <th>{{ sale.type.title  }}</th>
                                <td>{{ sale.msisdn.pointofsale.name }}</td>
                                <td>{{ sale.msisdn.profile.title }}</td>
                                <td>{{ sale.amount | number_format(0, ',', ' ')  }} F CFA</td>
                                <td>{{ sale.dComm | number_format(0, ',', ' ')  }} F CFA</td>
                                <td>{{ sale.dCommCalc  | number_format(0, ',', ' ')  }} F CFA</td>
                                <td>{{ sale.posComm | number_format(0, ',', ' ')  }} F CFA</td>
                                <td>{{ sale.posCommCalc | number_format(0, ',', ' ')  }} F CFA</td>
                                <td class="row-actions">
                                    <a href="{{ path('pointofsale_show', {'id': sale.msisdn.pointofsale.id}) }}"><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>

                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/sale/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction{% endblock %}

{% block body %}
    <div class="content-box">
        <div class="element-wrapper">
            <div class="row">
                <div class="col-lg-10">
                    <h5 class="element-header">Liste des transactions CSIN / AGNT / ...</h5>
                </div>
                <div class="col-lg-2 text-right">
                    {% if 'ROLE_SUPER_ADMIN' in app.user.roles() %}
                        <a href="{{ path('trader_add') }}" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> Ajouter</a>
                    {% endif %}
                </div>
            </div>
            <div class="element-box">
                <div class="table-responsive">
                    <table id="dataTable1" width="100%" class="table table-striped table-lightfont">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Nbre Dépot</th>
                            <th>Valeur Dépot</th>
                            <th>Commission Dépot</th>
                            <th>Nbre Retrait</th>
                            <th>Valeur Retrait</th>
                            <th>Commission Retrait</th>
                            <th>Total Commission</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for column in columnHeaders %}
                                <tr>
                                    <td class="text-center">{{ column.day }}</td>
                                    <td class="text-right">
                                        {% for sale in sales %}
                                            <strong>{% if column.day == sale.day and sale.title == 'AGNT' %} {{ sale.total | number_format(0, ',', ' ') }}{% endif %}</strong>
                                        {% endfor %}
                                    </td>
                                    <td class="text-right">
                                        {% for sale in sales %}
                                            {% if column.day == sale.day and sale.title == 'AGNT' %} {{ sale.amount | number_format(0, ',', ' ') }} F CFA{% endif %}
                                        {% endfor %}
                                    </td>
                                    <td class="text-right">
                                        {% for sale in sales %}{% if column.day == sale.day and sale.title == 'AGNT' %} {{ sale.dComm | number_format(0, ',', ' ') }} F CFA{% endif %}{% endfor %}</td>
                                    <td class="text-right">
                                        {% for sale in sales %}
                                            <strong>{% if column.day == sale.day and sale.title == 'CSIN' %} {{ sale.total | number_format(0, ',', ' ') }}{% endif %}</strong>
                                        {% endfor %}
                                    </td>
                                    <td class="text-right">
                                        {% for sale in sales %}
                                            {% if column.day == sale.day and sale.title == 'CSIN' %} {{ sale.amount | number_format(0, ',', ' ') }} F CFA{% endif %}
                                        {% endfor %}
                                    </td>
                                    <td class="text-right">
                                        {% for sale in sales %}
                                            {% if column.day == sale.day and sale.title == 'CSIN' %} {{ sale.dComm | number_format(0, ',', ' ') }} F CFA{% endif %}
                                        {% endfor %}
                                    </td>
                                    <td class="text-right"><strong>{{ column.dComm | number_format(0, ',', ' ') }}F CFA</strong></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/sale/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Ventes
{% endblock %}
{% block body %}
    {{ dump(sale)}}
    {{ dump(sale.calcCommission) }}
    {{ dump(sale.simProfile) }}
{% endblock %}